version: 2.1

defaults:
    - &morningCron "30 11 * * *"
    - &middayCron  "0 17 * * *"
    - &overnightCron "0 8 * * *"

    - devBranchFilter: &devBranchFilter
        filters: {branches: {only: [ 'develop']}}
    - masterBranchFilter: &masterBranchFilter
        filters: {branches: {only: ['main']}}
    - na_dev_build: &naDevBuildDef
        build:
            name: "build-development"
    - na_staging_build: &naStagingBuildDef
        build:
            name: "build-staging"

workflows:
    version: 2
    commit:
        jobs:
            - build:
                name: commit
    # NOTE: All Schedules are UTC
    na-development-morning: &naDevMorning
        triggers:
            - schedule:
                cron: *morningCron
                <<: *devBranchFilter
        jobs:
            - <<: *naDevBuildDef
    na-development-midday:
        <<: *naDevMorning
        triggers:
            - schedule:
                cron: *middayCron
                <<: *devBranchFilter
    na-development-overnight:
        <<: *naDevMorning
        triggers:
            - schedule:
                cron: *overnightCron
                <<: *devBranchFilter

jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run:
                name: Get submodules
                command: git submodule init && git submodule update
            - restore_cache:
                key: storefront-node_modules-{{ checksum "package.json" }}
            - run:
                name: Install npm packages
                command: npm ci || npm install
            - save_cache:
                key: storefront-node_modules-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Run tests
                command: npm run lint && npm run cover
            - store_artifacts:
                path: /tmp/sfcc/artifacts
                destination: sfcc
