branches:
# Each branch entry is an array of environments to deploy to.
  develop:
    - dev-na04
    - dev-eu03
    - dev-ua03
    - dev-ap01
  main:
    - stg-na04
    - stg-eu03
    - stg-ua03
    - stg-ap01
  release:
    - stg-na04
    - stg-eu03
    - stg-ua03
    - stg-ap01
    - stg-ua002
    - stg-eu02
environments:
# Each environment configuration has the following structure
# instance:
#   host: // the `blah-blah-blah.demandware.net` hostname
#   region: // one of `na`,`emea`,`apac` - this tells the deployer to pull the right metadata
#   instanceType: // one of `dev`, `stg`, 'prd' - this also tells the deployer to pull the right metadata,
#                 // or for `prd` instances, that `replication` should be used for deployment rather than
#                 // uploading code/metadata directly
#   certURL: // the `cert.blah.blah.blah.demandware.net` hostname for 2FA deploys.  Only relevant for `stg` environments
#   test:  // (optional) Configuration data for kicking off automation tests
#     url: // the URL of the test suite to run
#     formData: // any form-data required to supply parameters on the post
#   replication: (optional) Required for `instanceType: prd`
#     host:  // The staging host where the job is defined for this prd instance
#     jobId: // The job ID on that staging host that is configured to run code and metadata replications
  dev-na04:
    host: development-na04-underarmour.demandware.net
    region: na
    instanceType: dev
    mode: production
    test:
      url: https://ci.zebrunner.com/job/ua-ecomm/job/phoenix-auto-qa/view/CRON/job/ECOMM-HEALTHCHECK-CRON/buildWithParameters?token=ciStart
      formData: locale=en_US
  stg-na04:
    host: staging-na04-underarmour.demandware.net
    region: na
    mode: production
    instanceType: stg
    certURL: cert.staging.na04.underarmour.demandware.net
    test:
      url: https://ci.zebrunner.com/job/ua-ecomm/job/phoenix-auto-qa/view/CRON/job/ECOMM-HEALTHCHECK-CRON/buildWithParameters?env=STAG&token=ciStart
      formData: locale=en_US
  dev-eu03:
    host: development-eu03-ua.demandware.net
    region: emea
    mode: production
    instanceType: dev
  stg-eu03:
    host: staging-eu03-ua.demandware.net
    region: emea
    mode: production
    instanceType: stg
    certURL: cert.staging.eu03.ua.demandware.net
  dev-ap01:
    host: development-ap01-underarmour.demandware.net
    region: apac
    mode: production
    instanceType: dev
  stg-ap01:
    host: staging-ap01-underarmour.demandware.net
    region: apac
    mode: production
    instanceType: stg
    certURL: cert.staging.ap01.underarmour.demandware.net
  dev-ua03:
    host: development-ua03-underarmour.demandware.net
    mode: production
    region: na-oms
    instanceType: dev
  stg-ua03:
    host: staging-ua03-underarmour.demandware.net
    region: na
    mode: production
    instanceType: stg
    certURL: cert.staging.ua03.underarmour.demandware.net
  prd-ua03:
    host: production-ua03-underarmour.demandware.net
    instanceType: prd
    replication:
      host: staging-ua03-underarmour.demandware.net
      jobId: CodeAndDataDeploy
  stg-ua002:
    host: staging-ua002-underarmour.demandware.net
    region: apac
    mode: production
    instanceType: stg
    certURL: cert.staging.ua002.underarmour.demandware.net
  stg-eu02:
    host: staging-eu02-underarmour.demandware.net
    region: emea
    mode: production
    instanceType: stg
    certURL: cert.staging.eu02.underarmour.demandware.net
