var LOYALTY_STATUS = {
    ENROLLED: 'ENROLLED',
    UNENROLLED: 'UNENROLLED'
};

const LOYALTY_REWARD_FLOW_TYPE = {
    ONLINE_DOLLAR_OFF: 'ONLINE_DOLLAR_OFF',
    INSTORE_DOLLAR_OFF: 'INSTORE_DOLLAR_OFF',
    FREE_PRODUCT: 'FREE_PRODUCT',
    BIRTHDAY_REWARD: 'BIRTHDAY_REWARD',
    SWEEPSTAKE: 'SWEEPSTAKE',
    ATHLETE_ASSESSMENT: 'ATHLETE_ASSESSMENT',
    MEMBERPERK_URLCTA: 'MEMBERPERK_URLCTA'
};

const LOYALTY_PREFIX = 'LYLD';

module.exports.LOYALTY_PREFIX = LOYALTY_PREFIX;
module.exports.LOYALTY_STATUS = LOYALTY_STATUS;
module.exports.LOYALTY_REWARD_FLOW_TYPE = LOYALTY_REWARD_FLOW_TYPE;
