name: 'Lint and Test'
description: 'Run Lint/Tests'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Lint / Test
      run: .build/post-checkout.sh
      shell: bash
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage
