name: Run Lint/Tests
on:
  pull_request_target:
    branches:
      - main
      - dragon
      - develop
jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_SSH_KEY }}
          persist-credentials: true
          submodules: recursive
      - uses: ./.github/actions/lint-and-test
